version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
        POSTGRES_DB: cards
        POSTGRES_USER: ouaf
        POSTGRES_PASSWORD: ouaf
    restart: always
    ports:
      - 5432:5432