version: '3.1'
services:
  postgres:
    image: postgres:latest
    environment:
        POSTGRES_DB: atelier3
        POSTGRES_USER: atelier3
        POSTGRES_PASSWORD: atelier3
    restart: always
    ports:
      - 5432:5432

  nginx:
    build: ./src/main/resources/nginx
    restart: always
    ports:
      - 80:80
