version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
        POSTGRES_DB: cards
        POSTGRES_USER: ouaf
        POSTGRES_PASSWORD: ouaf
    restart: always
    ports:
      - 5432:5432

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/resources:/usr/share/nginx/html
    restart: always
    ports:
      - 80:80
