name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Start PostgreSQL with Docker Compose
        run: |
          docker-compose -f atelier3/commons/src/main/resources/database/docker-compose.yml up -d
          export DB_PASSWORD=$DB_PASSWORD

      - name: Install Commons with Maven
        run: mvn -B install --file atelier3/commons/pom.xml

      - name: Install Card with Maven
        run: mvn -B install --file atelier3/card-server/pom.xml
